#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Regenerate the private dictionary a pack ships (Wave 4a section 5.3).

What a vendor calls a private element, and what VR it has, is knowledge about
scanners and not about this engine, so it travels as pack data. This writes
that data from pydicom's private dictionary, which pydicom generates from the
GDCM project's; the provenance and the licences are written into the file's
header so the pack's PROVENANCE.md can point at it.

    python3 tools/private-dict/extract.py [--ref TAG] > packs/mri/private-dictionary.tsv

Tab-separated, one element a line: creator, group as four hex digits, offset
within the block as two, VR, VM, name. Comment lines start with `#`. A creator
that is a UID rather than a name is kept: an archive that reserves a block
under it is addressed by it.
"""
from __future__ import annotations

import argparse
import ast
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/pydicom/pydicom/{ref}/src/pydicom/_private_dict.py"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", default="v3.0.1", help="the pydicom tag or commit to read")
    ap.add_argument("--file", help="a local copy of _private_dict.py instead of fetching")
    a = ap.parse_args()
    if a.file:
        text = open(a.file, encoding="utf-8").read()
        source = a.file
    else:
        source = URL.format(ref=a.ref)
        text = urllib.request.urlopen(source).read().decode("utf-8")
    # The file is one dict literal assigned to private_dictionaries; read it
    # as a literal rather than importing it, so nothing runs.
    start = text.index("{", text.index("private_dictionaries"))
    table = ast.literal_eval(text[start:].strip())
    rows = []
    skipped = 0
    for creator, elements in table.items():
        for tag, (vr, vm, name, _retired) in elements.items():
            # Keys are `GGGGxxEE`, or `GGGGEEEE` where a vendor fixed the slot;
            # both address the offset, the low byte.
            group = tag[:4].upper()
            offset = tag[-2:].upper()
            # A wildcard offset (`xxXX`) names a range, not an element, and
            # cannot be addressed; a handful of entries are that.
            if not all(c in "0123456789ABCDEF" for c in group + offset):
                skipped += 1
                continue
            # An entry the source left unnamed is said to be unknown rather
            # than left as an empty field a reader would trip on.
            rows.append((creator, group, offset, vr or "UN", vm or "1", name or "Unknown"))
    rows.sort()
    out = sys.stdout
    out.write("# The private dictionary the pack ships (Wave 4a section 5.3).\n")
    out.write(f"# Generated by tools/private-dict/extract.py from {source}\n")
    out.write("# pydicom is MIT licensed; its private dictionary is generated from the GDCM\n")
    out.write("# project's, which is BSD 3-clause. Both notices are in the pack's\n")
    out.write("# PROVENANCE.md. Columns: creator, group, offset, vr, vm, name.\n")
    out.write(f"# {len(table)} creators, {len(rows)} elements; {skipped} wildcard entries left out.\n")
    for r in rows:
        out.write("\t".join(r) + "\n")


if __name__ == "__main__":
    main()
